export AZURE_WA_SITE=$(eval "echo \$AZURE_WA_SITE_${TRAVIS_BRANCH}")
export AZURE_WA_USERNAME=$(eval "echo \$AZURE_WA_USERNAME_${TRAVIS_BRANCH}")
export AZURE_WA_PASSWORD=$(eval "echo \$AZURE_WA_PASSWORD_${TRAVIS_BRANCH}")